#!/usr/bin/env bash
# owed-work-stubs.sh — the RED DEMONSTRATION for owed-work-recall.sh. (#172, #178)
#
# `docs/DELIVERY.md § Proof that a test can fail`: a test only earns its place if
# it would fail on the bug it names. `owed-work-recall.sh` is green against
# `owed-work.sh`, AND GREEN AGAINST THE REAL DETECTOR PROVES NOTHING — a corpus
# that asserted nothing would be just as green. This script is what makes the
# green mean something.
#
# HOW THE DEMONSTRATION IS MADE HONEST. Five detectors are generated from ONE
# template, differing in a single `DEFECT` flag. The first has no defect and must
# go GREEN; the other four each reproduce a documented failure and must go RED.
# Generating them from one template is the whole method.
# `docs/DELIVERY.md § Red for the wrong reason` excludes a demonstration that is
# red because something failed to build or never reached its assertion, and four
# independently-written stubs would each be red for reasons nobody could
# attribute to a defect. Here the four differ from a detector
# that PASSES THE WHOLE CORPUS by one behaviour each, so every red is that
# behaviour and nothing else.
#
# THE `none` STUB IS NOT A FORMALITY. It is a second, independent implementation
# of the contract, written from the same criteria as the corpus and by the same
# hand, and it must satisfy every check. That is what shows the corpus is
# SATISFIABLE rather than tautologically red — and it is what would distinguish
# "the real detector is wrong" from "the corpus over-specifies" if the two ever
# disagreed. Neither of them is the corpus's author's; the criteria are.
#
# THE FOUR DEFECTS, and the failure each one reproduces:
#   two_state       folds `undeclared` into `clear` and never exits 3. Measured
#                   2026-09-07: all four open PRs carried ZERO declared
#                   revision_packet/judgment comments, so this detector prints
#                   #135 — which held an undischarged cycle-4 packet — as nothing
#                   owed. #172's own bug, reproduced by its fix.
#   prose           keys off HEADING TEXT instead of the declared `artifact:` key
#                   (#172 criterion 2). This is the 2026-09-06 survey's two ad-hoc
#                   greps: #147 called "zero judge ledgers" when it had four, #154
#                   "no packet found" when a packet existed and had been worked.
#   quiet_fail      exits 0 when a source is unreadable (#172 criterion 4, the
#                   `fingerprint.sh` precedent): an unreadable source is not a
#                   quiet queue.
#   b2_discharged   lets a `judgment` discharge the validation question (#178
#                   criterion 3): the mandatory last lane silently skipped, which
#                   is PR #135 cycles 4 and 5 and PR #154 cycle 6.
#
# Hermetic: everything generated under mktemp, nothing written outside it, no
# network, no repository state. The corpus it drives is hermetic in its own right.
# Usage: scripts/loop/tests/owed-work-stubs.sh
# Exit:  0 the `none` stub passed AND all four defective stubs were caught
#        1 any stub behaved otherwise — which is a corpus that does not discriminate

set -u
DIR="$(cd "$(dirname "$0")" && pwd)"
CORPUS="$DIR/owed-work-recall.sh"

TMP="$(mktemp -d)" || TMP=''
[ -n "$TMP" ] && [ -d "$TMP" ] || {
  printf 'FAIL  mktemp -d gave no usable directory; refusing to run\n'; exit 1; }
trap 'rm -rf "$TMP"' EXIT

[ -f "$CORPUS" ] || { printf 'FAIL  construction · the corpus is not at %s\n' "$CORPUS"; exit 1; }

# ---------------------------------------------------------------------------
# THE TEMPLATE. One contract-faithful detector; `__DEFECT__` is substituted per
# stub and is the ONLY difference between them.
# ---------------------------------------------------------------------------
cat > "$TMP/template" <<'TEMPLATE'
#!/usr/bin/env bash
# Generated by owed-work-stubs.sh. Not a deliverable — a control.
set -u
DEFECT="__DEFECT__"
GH="${GH:-gh}"
R='repos/{owner}/{repo}'

usage() { echo "usage: owed-work.sh [pr-number ...]" >&2; }

if [ "$#" -gt 0 ]; then
  for a in "$@"; do
    case "$a" in ''|*[!0-9]*) usage; exit 2 ;; esac
  done
  PRS="$*"
else
  PRS="$("$GH" pr list --state open --limit 200 --json number --jq '.[].number' 2>/dev/null)"; lrc=$?
  if [ "$lrc" -ne 0 ]; then
    echo "owed_work: 0 PR(s) read"
    echo "summary: owed 0 · clear 0 · undeclared 0 · unreadable 1"
    exit 2
  fi
fi

n_owed=0; n_clear=0; n_undecl=0; n_unread=0; n_read=0
TABLE=''; OWED=''; UNDECL=''; UNREAD=''

secs() { date -u -d "$1" +%s 2>/dev/null || echo 0; }

for pr in $PRS; do
  # --- the comment records ----------------------------------------------------
  if [ "$DEFECT" = prose ]; then
    # DEFECT: identify artifacts by HEADING TEXT, never by the declared key.
    recs="$("$GH" api "$R/issues/$pr/comments" --paginate --jq 'RAWBODY' 2>/dev/null)"; crc=$?
    recs="$(printf '%s\n' "$recs" | awk '
      function flush() {
        if (ts == "") return
        val = (body ~ /(^|[^0-9A-Za-z_-])@?validation-agent([^0-9A-Za-z_-]|$)/) ? 1 : 0
        printf "%s %s %s %s\n", ts, (art == "" ? "-" : art), (rev == "" ? "-" : rev), val
      }
      /^#REC / { flush(); ts = $2; art = ""; rev = ""; body = ""; next }
      { body = body $0 "\n"
        if ($0 ~ /^#+ /) {
          if (art == "" && tolower($0) ~ /revision packet|required changes/) art = "revision_packet"
          else if (art == "" && tolower($0) ~ /review ledger|panel|review board/) art = "review_ledger"
          else if (art == "" && tolower($0) ~ /judgment|ruling/) art = "judgment"
          else if (art == "" && tolower($0) ~ /validation/) { art = "reviewer_verdict"; rev = "validation-agent" }
        } }
      END { flush() }')"
  else
    recs="$("$GH" api "$R/issues/$pr/comments" --paginate --jq 'DECLARED' 2>/dev/null)"; crc=$?
  fi
  dates="$("$GH" api "$R/pulls/$pr/commits" --paginate --jq '.[].commit.committer.date' 2>/dev/null)"; drc=$?

  if [ "$crc" -ne 0 ] || [ "$drc" -ne 0 ] || [ -z "$dates" ]; then
    n_unread=$((n_unread + 1))
    TABLE="$TABLE
$(printf '#%-5s %-11s %s' "$pr" "unreadable" "a source could not be read")"
    UNREAD="$UNREAD
  #$pr a source could not be read"
    continue
  fi
  n_read=$((n_read + 1))

  # The API returns commits oldest first, so the newest is the last line. Taken by
  # parameter expansion rather than `sort | tail`: this template runs some 1,400
  # times across the five stubs, and on this host a subprocess costs more than the
  # whole comparison. ISO-8601 Z timestamps compare correctly as strings, which is
  # why `date` is reached for only once, for the gap.
  newest_commit="${dates##*$'\n'}"

  # ONE pass for every derived value: the newest packet, the newest ledger and
  # whether it names the lane, the newest ruling after that ledger, and the newest
  # validation verdict after it.
  vals="$(printf '%s\n' "$recs" | awk '
    $2 == "revision_packet" { pkt = $1 }
    $2 == "review_ledger"   { led = $1; ledval = $4 }
    $2 == "judgment"        { j[++nj] = $1 }
    $2 == "reviewer_verdict" && $3 ~ /^@?validation-agent$/ { v[++nv] = $1 }
    END {
      if (led != "") {
        for (i = 1; i <= nj; i++) if (j[i] > led && j[i] > rule) rule = j[i]
        for (i = 1; i <= nv; i++) if (v[i] > led && v[i] > ver)  ver  = v[i]
      }
      printf "%s|%s|%d|%s|%s\n", pkt, led, ledval + 0, rule, ver
    }')"
  IFS='|' read -r pkt led led_names_val rule ver <<EOF
$vals
EOF

  # --- condition A: the newest packet, newer than the newest commit -------------
  if [ -z "$pkt" ]; then packet=undeclared
  elif [[ "$pkt" > "$newest_commit" ]]; then
    packet=owed
    gap=$(( ( $(secs "$pkt") - $(secs "$newest_commit") ) / 86400 ))
    OWED="$OWED
  #$pr revision_packet $pkt is $gap day(s) newer than the newest commit $newest_commit"
  else packet=clear
  fi

  # --- condition B1: a panel with no ruling after it ---------------------------
  if [ -z "$led" ]; then ruling=undeclared
  elif [ -n "$rule" ]; then ruling=clear
  else ruling=owed
    OWED="$OWED
  #$pr review_ledger $led has no judgment after it"
  fi

  # --- condition B2: the mandatory last lane -----------------------------------
  # DEFECT: a ruling closes the validation question. It does not — #135 c4/c5.
  [ "$DEFECT" = b2_discharged ] && [ -n "$rule" ] && ver="$rule"
  if [ -z "$led" ]; then validation=undeclared
  elif [ "$led_names_val" -eq 0 ]; then validation=n/a
  elif [ -n "$ver" ]; then validation=clear
  else validation=owed
    OWED="$OWED
  #$pr review_ledger $led names @validation-agent and has no validation verdict after it"
  fi

  # DEFECT: two states. `undeclared` becomes `clear` and the distinction is gone.
  if [ "$DEFECT" = two_state ]; then
    [ "$packet"     = undeclared ] && packet=clear
    [ "$ruling"     = undeclared ] && ruling=clear
    [ "$validation" = undeclared ] && validation=clear
  fi

  case "$packet$ruling$validation" in
    *owed*)       state=owed;       n_owed=$((n_owed + 1)) ;;
    *undeclared*) state=undeclared; n_undecl=$((n_undecl + 1))
                  UNDECL="$UNDECL
  #$pr no declared artifact of at least one class — cannot be judged; this is NOT \"nothing owed\"" ;;
    *)            state=clear;      n_clear=$((n_clear + 1)) ;;
  esac

  TABLE="$TABLE
$(printf '#%-5s %-11s packet=%-11s ruling=%-11s validation=%s' \
    "$pr" "$state" "$packet" "$ruling" "$validation")"
done

printf 'owed_work: %d PR(s) read\n' "$n_read"
[ -n "$TABLE" ]  && printf '%s\n' "${TABLE#
}"
[ -n "$OWED" ]   && { printf 'owed:\n'; printf '%s\n' "${OWED#
}"; }
[ -n "$UNDECL" ] && { printf 'undeclared:\n'; printf '%s\n' "${UNDECL#
}"; }
[ -n "$UNREAD" ] && { printf 'unreadable:\n'; printf '%s\n' "${UNREAD#
}"; }
printf 'summary: owed %d · clear %d · undeclared %d · unreadable %d\n' \
  "$n_owed" "$n_clear" "$n_undecl" "$n_unread"

# Precedence 2 > 1 > 3 > 0.
# DEFECT: an unreadable source exits 0 — a quiet queue, which is what
# `fingerprint.sh` was fixed to stop being.
if [ "$n_unread" -gt 0 ] && [ "$DEFECT" != quiet_fail ]; then exit 2; fi
[ "$n_owed"   -gt 0 ] && exit 1
[ "$n_undecl" -gt 0 ] && exit 3
exit 0
TEMPLATE

mk() { # mk <defect>
  sed "s/__DEFECT__/$1/" "$TMP/template" > "$TMP/$1.sh"
  chmod +x "$TMP/$1.sh"
  cmp -s "$TMP/template" "$TMP/$1.sh" && {
    printf 'FAIL  construction · the %s stub is byte-identical to the template — a stub that mutates nothing proves nothing\n' "$1"
    exit 1; }
}
for d in none two_state prose quiet_fail b2_discharged; do mk "$d"; done

fails=0
report() { # report <defect> <must-be: green|red>
  out="$(bash "$CORPUS" "$TMP/$1.sh" 2>&1)"; rc=$?
  n_pass="$(printf '%s\n' "$out" | grep -c '^PASS' || true)"
  n_fail="$(printf '%s\n' "$out" | grep -c '^FAIL' || true)"
  if [ "$2" = green ]; then
    if [ "$rc" -eq 0 ]; then
      printf 'PASS  %-14s contract-faithful · %s checks passed, corpus rc 0\n' "$1" "$n_pass"
    else
      printf 'FAIL  %-14s contract-faithful stub did NOT satisfy the corpus (rc %s, %s red)\n' "$1" "$rc" "$n_fail"
      printf '%s\n' "$out" | grep '^FAIL' | sed 's/^/        /'
      fails=$((fails + 1))
    fi
  else
    if [ "$rc" -ne 0 ] && [ "$n_fail" -gt 0 ]; then
      printf 'PASS  %-14s CAUGHT · %s checks red, %s still green, corpus rc %s\n' "$1" "$n_fail" "$n_pass" "$rc"
      printf '%s\n' "$out" | grep '^FAIL' | sed 's/^\(FAIL  \)/        red: /' \
        | cut -c1-118 | head -8
      [ "$n_fail" -gt 8 ] && printf '        red: … and %s more\n' "$((n_fail - 8))"
    else
      printf 'FAIL  %-14s NOT CAUGHT — the corpus is green against a detector with this defect\n' "$1"
      fails=$((fails + 1))
    fi
  fi
  printf '\n'
}

printf 'corpus: %s\n\n' "$CORPUS"
report none           green
report two_state      red
report prose          red
report quiet_fail     red
report b2_discharged  red

[ "$fails" -eq 0 ] || { printf '%s stub(s) behaved wrongly\n' "$fails"; exit 1; }
printf 'the corpus discriminates: one contract-faithful detector passes it and four defective ones do not\n'
exit 0
