package zonesync

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"time"
)

// Zone is one record of the all-zones response, mapped to the columns of
// `zone_incoming`.
//
// The mapping is `migrations/README.md § The zone ingest field mapping` and this
// type implements it rather than restating it: fourteen fields for the staging
// table's fourteen columns, in its declared order, with the four nullable ones
// as pointers so an absent field is distinguishable from a zero one. `type.name`
// is read and dropped, and `geom`, `first_seen_at` and `last_changed_at` are not
// here at all — the first is generated by PostgreSQL and the other two are the
// merge's to write.
type Zone struct {
	ID             int32
	Name           string
	Latitude       float64
	Longitude      float64
	DateCreated    time.Time
	TotalTakeovers int32
	TakeoverPoints int16
	PointsPerHour  int16
	TypeID         *int16
	RegionID       int16
	RegionName     string
	RegionCountry  *string
	AreaID         *int32
	AreaName       *string
}

// wireZone is one record as the API sends it.
//
// EVERY FIELD IS A POINTER, INCLUDING THE ONES MEASURED AT 100%. The reason is
// that `0` and `""` are legitimate values here — a zone with no takeovers, an
// empty name — so a value type cannot tell a field the response omitted from a
// field the response sent as zero. Decoding a required field that is absent must
// be an error and not a silent zero: `Architecture.md § Retrieving zones`
// measures nine of these on every record of the complete response, so a record
// missing one is a response this system does not understand rather than a zone
// with a default.
//
// The genuinely optional ones are `type` and, inside `region`, `country` and
// `area`. Their absence is the ordinary case and never an anomaly, which that
// same section states and the schema's nullability follows.
type wireZone struct {
	ID             *int32      `json:"id"`
	Name           *string     `json:"name"`
	Latitude       *float64    `json:"latitude"`
	Longitude      *float64    `json:"longitude"`
	DateCreated    *string     `json:"dateCreated"`
	TotalTakeovers *int32      `json:"totalTakeovers"`
	TakeoverPoints *int16      `json:"takeoverPoints"`
	PointsPerHour  *int16      `json:"pointsPerHour"`
	Type           *wireType   `json:"type"`
	Region         *wireRegion `json:"region"`
}

type wireType struct {
	ID *int16 `json:"id"`
}

type wireRegion struct {
	ID      *int16    `json:"id"`
	Name    *string   `json:"name"`
	Country *string   `json:"country"`
	Area    *wireArea `json:"area"`
}

type wireArea struct {
	ID   *int32  `json:"id"`
	Name *string `json:"name"`
}

// dateCreatedLayouts are the forms `dateCreated` is accepted in, tried in order.
//
// THIS LIST IS UNVERIFIED AGAINST A LIVE RESPONSE. `Architecture.md § Retrieving
// zones` records that the field is present on every record and that it is
// mutable; it records no serialisation format, and no response was available to
// the work that wrote this. The list is therefore tolerant of the ordinary
// shapes rather than derived from an observation, and a value matching none of
// them fails the run loudly with the value in the message — which is the
// behaviour that gets the list corrected rather than a zero timestamp written to
// every row.
var dateCreatedLayouts = []string{
	time.RFC3339,
	"2006-01-02T15:04:05Z0700",
	"2006-01-02T15:04:05",
	"2006-01-02 15:04:05Z07:00",
	"2006-01-02 15:04:05",
	"2006-01-02",
}

// ParseAllZones maps an all-zones response body onto the staging rows.
//
// It is a pure function over the bytes, and deliberately so: it is the whole of
// the ingest mapping, it is the step most likely to be wrong, and holding it
// away from both the network and the database is what lets it be tested against
// a fixture rather than against a live API and a live store.
//
// It refuses the whole response on the first record it cannot map. A partial
// merge is not available to it — the merge is one transaction by design, per
// `Architecture.md § The sync write path` — so the choice is between refusing a
// response this system does not understand and silently dropping records from a
// feed whose completeness the staging assertions are about to be measured on.
func ParseAllZones(body []byte) ([]Zone, error) {
	dec := json.NewDecoder(bytes.NewReader(body))

	open, err := dec.Token()
	if err != nil {
		return nil, fmt.Errorf("reading the start of the response: %w", err)
	}

	if delim, ok := open.(json.Delim); !ok || delim != '[' {
		return nil, fmt.Errorf("the response starts with %v, want a JSON array of zone records", open)
	}

	zones := make([]Zone, 0, 128)

	for index := 0; dec.More(); index++ {
		var wire wireZone

		if err := dec.Decode(&wire); err != nil {
			return nil, fmt.Errorf("decoding record %d: %w", index, err)
		}

		zone, err := wire.zone()
		if err != nil {
			return nil, fmt.Errorf("record %d: %w", index, err)
		}

		zones = append(zones, zone)
	}

	if _, err := dec.Token(); err != nil {
		return nil, fmt.Errorf("reading the end of the response: %w", err)
	}

	// Anything after the array is a response that is not the one this reads.
	if _, err := dec.Token(); !errors.Is(err, io.EOF) {
		return nil, errors.New("the response carries more than the zone array")
	}

	return zones, nil
}

// zone maps one decoded record. The required fields are named individually so
// the error says which one was missing rather than that the record was bad.
func (w wireZone) zone() (Zone, error) {
	var z Zone

	if w.ID == nil {
		return z, errors.New("no id")
	}

	if w.Name == nil {
		return z, fmt.Errorf("zone %d: no name", *w.ID)
	}

	if w.Latitude == nil || w.Longitude == nil {
		return z, fmt.Errorf("zone %d: no coordinate", *w.ID)
	}

	if w.DateCreated == nil {
		return z, fmt.Errorf("zone %d: no dateCreated", *w.ID)
	}

	if w.TotalTakeovers == nil || w.TakeoverPoints == nil || w.PointsPerHour == nil {
		return z, fmt.Errorf("zone %d: no totalTakeovers, takeoverPoints or pointsPerHour", *w.ID)
	}

	if w.Region == nil || w.Region.ID == nil || w.Region.Name == nil {
		return z, fmt.Errorf("zone %d: no region id or name", *w.ID)
	}

	created, err := parseDateCreated(*w.DateCreated)
	if err != nil {
		return z, fmt.Errorf("zone %d: %w", *w.ID, err)
	}

	z = Zone{
		ID:             *w.ID,
		Name:           *w.Name,
		Latitude:       *w.Latitude,
		Longitude:      *w.Longitude,
		DateCreated:    created,
		TotalTakeovers: *w.TotalTakeovers,
		TakeoverPoints: *w.TakeoverPoints,
		PointsPerHour:  *w.PointsPerHour,
		RegionID:       *w.Region.ID,
		RegionName:     *w.Region.Name,
		RegionCountry:  w.Region.Country,
	}

	// `type` is absent from most records, and `type.name` is read and dropped:
	// one name per id with no disagreement anywhere in the corpus, so the id
	// carries everything. Both facts are in the mapping cited on Zone above.
	if w.Type != nil {
		z.TypeID = w.Type.ID
	}

	// `region.area` is absent for reasons `Architecture.md § The region
	// hierarchy is not a tree` records, and its two subkeys travel together.
	if w.Region.Area != nil {
		z.AreaID = w.Region.Area.ID
		z.AreaName = w.Region.Area.Name
	}

	return z, nil
}

// parseDateCreated reads the one timestamp the response carries.
//
// A value with no zone is read as UTC rather than as the host's local zone. The
// host's zone is not a property of the data, and reading it that way would make
// the stored instant depend on where the service happens to run — a difference
// that shows up as a shifted takeover-rate denominator rather than as an error.
func parseDateCreated(raw string) (time.Time, error) {
	for _, layout := range dateCreatedLayouts {
		if t, err := time.ParseInLocation(layout, raw, time.UTC); err == nil {
			return t.UTC(), nil
		}
	}

	return time.Time{}, fmt.Errorf("dateCreated=%q matches none of the accepted layouts %v", raw, dateCreatedLayouts)
}
